version: '3.6'
services:
  # exam-app:
  #   build: .
  #   container_name: exam-app
  #   env_file:
  #     - .env.production
  #   ports:
  #     - 8080:8080
  #   depends_on:
  #     - redis
  #     - postgres
  #   networks:
  #     - exam_net

  postgres:
    image: postgres:15
    container_name: exam-postgres
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: tuan-dung-exam
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
      LANG: C.UTF-8
      TZ: Asia/Ho_Chi_Minh
    ports:
      - 15432:5432
    volumes:
      - postgres-data:/var/lib/postgres/data
    networks:
      - exam_net

  redis:
    image: 'redis:6-alpine'
    container_name: exam-redis
    ports:
      - 16379:6379
    volumes:
      - redis-data:/var/lib/redis/data
    networks:
      - exam_net

volumes:
  postgres-data:
  redis-data:
  
networks:
  exam_net:
    driver: bridge
