import { config } from 'dotenv';

config();

const APP_NAME_PREFIX = process.env.APP_NAME.toUpperCase();

export const CACHE_CONSTANT = {
  SESSION_STUDENT_PREFIX: `${APP_NAME_PREFIX}:SESSION_STUDENT_ID:`,
  SESSION_TEACHER_PREFIX: `${APP_NAME_PREFIX}:SESSION_TEACHER_ID:`,
  GATEWAY_STUDENT_PREFIX: `${APP_NAME_PREFIX}:GATEWAY_STUDENT`,
  GATEWAY_TEACHER_PREFIX: `${APP_NAME_PREFIX}:GATEWAY_TEACHER`,
  CHANNEL_CONVERSATION_PREFIX: `${APP_NAME_PREFIX}:CHANNEL_CONVERSATION:`,
  ASSIGNMENT_PREFIX: `${APP_NAME_PREFIX}:ASSIGNMENT_SESSION:`,
};
